version: '3.7'
services: 
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3307"
    environment: 
      MYSQL_DATABASE: 'maltego'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: "venkat@123"
  app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - "8081:81"
    volumes:
      - ./:/var/www/html       